# use_frameworks!
# 以动态库加载framework
# 不使用就以static libraires方式

platform :ios, '10.0'

target 'ZWViewUtils_Example' do
  pod 'ZWViewUtils', :path => '../'

  target 'ZWViewUtils_Tests' do
    inherit! :search_paths

    
  end
end
